[build]
  command = "npx shadcn-ui@latest add button && npx shadcn-ui@latest add card && npm i && npm install recharts && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
