[build]
  command = "npm install @babel/plugin-proposal-private-property-in-object --save-dev && npm install && npm install recharts && CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
