[build]
  command = "npm i @babel/plugin-proposal-private-property-in-object --save-dev && npm i && npm install recharts && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
